"""GitHub delivery: one 'Contribution board' issue in your own scout repo.

The issue body is the live board (everything free, claimed-but-quiet and waiting for a
first review), rewritten on every run. When something changed, a comment mentioning
you carries the day's news, so it reaches the GitHub app and your email.

Two things keep the board polite if the repo is public:
- links go through redirect.github.com, which (as Dependabot does) avoids leaving a
  "mentioned this issue" note on every upstream issue;
- '@' in titles is neutralised so the board never pings anyone but you.
"""

LABEL = "oss-scout"
LABEL_COLOR = "0e8a16"
TITLE = "Contribution board"
MAX_COMMENT_LINES = 25
SECTION_LIMIT = 25          # items per board section; the rest are counted, not listed
MAX_COMMENTS = 100          # then the board moves to a fresh issue, so the page stays quick
BODY_LIMIT = 60000          # GitHub refuses issue bodies over 65,536 characters


def quiet_link(url):
    return url.replace("https://github.com/", "https://redirect.github.com/", 1)


def safe(text):
    return text.replace("@", "@​").replace("\n", " ")


def _ref(key):
    repo, number = key.rsplit("#", 1)
    return f"{repo.split('/')[-1]} {number}"


def _line(item):
    detail = f" — {safe(item.detail)}" if item.detail else ""
    return f"- [{_ref(item.key)}]({quiet_link(item.url)}) {safe(item.title)}{detail}"


def _capped(heading, items, limit=None, empty="Nothing right now.", more="see the board above"):
    lines = [f"### {heading} ({len(items)})", ""]
    if not items:
        lines.append(f"_{empty}_")
    shown = items if limit is None else items[:limit]
    lines += [_line(i) for i in shown]
    if limit is not None and len(items) > limit:
        lines.append(f"- _…and {len(items) - limit} more, {more}_")
    lines.append("")
    return lines


def render_board(digest, cfg, now, home_repo=None):
    cap = cfg.get("board_section_limit", SECTION_LIMIT)

    def _section(heading, items, empty="Nothing right now."):
        return _capped(heading, items, cap, empty=empty, more="not listed here")

    tool = f"[oss-scout](https://github.com/{home_repo})" if home_repo else "oss-scout"
    repos = ", ".join(r["repo"] for r in cfg["repos"])
    areas = ", ".join(sorted({lbl for r in cfg["repos"] for lbl in (r.get("labels") or ["everything"])}))
    d = cfg.get("discover") or {}
    lines = [f"Updated {now.strftime('%a %d %b %Y, %H:%M')} UTC · watching {safe(repos)}", "",
             f"Areas: {safe(areas)}", ""]
    if d.get("orgs"):
        labels = " or ".join(f"`{x}`" for x in (d.get("labels") or ["good first issue", "help wanted"]))
        lines += [f"Also looking across {safe(', '.join(d['orgs']))} for issues labelled {labels}.", ""]
    lines += ["## Needs you", ""]
    lines += _section("PRs to review on threads you're in", digest.board_followups,
                      empty="Nothing waiting for you.")
    lines += _section(f"Your PRs with no review after {cfg.get('ping_after_days', 7)}+ days", digest.board_my_waiting,
                      empty="None. The CNCF contributor FAQ suggests a polite ping after about a week.")
    lines += _section(f"Issues you claimed {cfg.get('claim_reminder_days', 14)}+ days ago with no PR",
                      digest.board_my_claims, empty="None.")
    lines += ["## To pick up", ""]
    lines += _section("Free in your areas", digest.board_free,
                      empty="No unclaimed issues in these areas today.")
    if d.get("orgs"):
        lines += _section(f"Free across {', '.join(d['orgs'])}", digest.board_discovered,
                          empty="Nothing new and unclaimed right now.")
    lines += _section(f"Claimed by someone else but quiet for {cfg.get('quiet_days', 45)}+ days", digest.board_quiet)
    lines += ["## To review", ""]
    lines += _section(f"PRs in your areas waiting {cfg.get('stale_review_days', 7)}+ days for a first review",
                      digest.board_queue)
    lines += [
        "---",
        "_Free means no linked PR, no claim comment and no blocking label. Claim detection is a "
        "heuristic, so read the whole thread and ask a maintainer before starting. Generated by "
        f"{tool}, which only reads public data._",
    ]
    if digest.errors:
        lines += ["", f"_Last run was partial: {len(digest.errors)} request(s) failed._"]
    body = "\n".join(lines) + "\n"
    if len(body) > BODY_LIMIT:
        body = body[:BODY_LIMIT].rsplit("\n", 1)[0] + "\n\n_Board cut short to fit GitHub's size limit. " \
               "Lower `board_section_limit` or watch fewer labels._\n"
    return body


def render_comment(digest, cfg, now):
    user = cfg["github_user"]
    lines = [f"@{user} · {now.strftime('%a %d %b')}", ""]
    if digest.baseline:
        c = digest.counts
        lines += [
            "**Watching from today.** From now on you'll get a comment here only when something changes.",
            "",
            f"{c.get('free', 0)} free · {c.get('quiet', 0)} claimed but quiet · "
            f"{c.get('blocked', 0)} blocked · {c.get('taken', 0)} taken"
            + (f" · {c['discovered']} free across your organisations" if "discovered" in c else "")
            + ". The full lists are in the issue above.",
            "",
        ]
    if digest.needs_you:
        lines += _capped("Needs you", digest.needs_you, MAX_COMMENT_LINES)
    if digest.to_pick:
        heading = "Most recent free issues" if digest.baseline else "New to pick up"
        lines += _capped(heading, digest.to_pick, MAX_COMMENT_LINES)
    if digest.discovered:
        lines += _capped("New across your organisations", digest.discovered, 5)
    if digest.review_queue:
        lines += _capped("Newly waiting for a first review", digest.review_queue, MAX_COMMENT_LINES)
    if digest.errors:
        lines += [f"_Partial scan: {len(digest.errors)} request(s) failed. First: {safe(digest.errors[0][:200])}_"]
    return "\n".join(lines).rstrip() + "\n"


def publish(writer, repo, digest, cfg, now, comment=True):
    """Create or update the board issue; add a comment when there's news.
    Returns the issue's URL."""
    body = render_board(digest, cfg, now, repo)
    issue = writer.find_open_issue(repo, LABEL)
    if issue is not None and issue.get("comments", 0) >= cfg.get("board_max_comments", MAX_COMMENTS):
        old = issue
        writer.ensure_label(repo, LABEL, LABEL_COLOR, "Daily contribution board from oss-scout")
        issue = writer.create_issue(repo, TITLE, body, [LABEL])
        writer.add_comment(repo, old["number"], f"Continued in #{issue['number']}, to keep this page quick to load.")
        writer.close_issue(repo, old["number"])
    elif issue is None:
        writer.ensure_label(repo, LABEL, LABEL_COLOR, "Daily contribution board from oss-scout")
        issue = writer.create_issue(repo, TITLE, body, [LABEL])
    else:
        writer.update_issue_body(repo, issue["number"], body)
    if comment:
        writer.add_comment(repo, issue["number"], render_comment(digest, cfg, now))
    return issue["html_url"]
